### ISSUE TITLE
Windows support / path separator errors

### ISSUE THREAD

**Issue by larsthorup** [istanbuljs/puppeteer-to-istanbul#53]
When cloning and running "npm test" in this repo on Windows 10, I get the errors below. On Linux "npm test" runs without errors. Tested on node@13. Appears to be an issue with path separator. Will investigate further.

```
  9 passing (148ms)
  3 failing

  1) output-files
       exposes a handler that appropriately handles colliding names:
     AssertionError: expected 'c:\\r\\github\\puppeteer-to-istanbul\\.nyc_output\\js\\sample_js\\block-else-not-covered-1.js' to include '.nyc_output/js/sample_js/block-else-not-covered-1.js'
      at Context.<anonymous> (test\output-files.js:23:20)
      at processImmediate (internal/timers.js:445:21)

  2) output-files
       appropriately handles modules required via http/https:
     AssertionError: expected 'c:\\r\\github\\puppeteer-to-istanbul\\.nyc_output\\js\\localhost_9000\\js\\index.js' to include 'js/index.js'
      at Context.<anonymous> (test\output-files.js:75:32)
      at processImmediate (internal/timers.js:445:21)

  3) puppeteer-to-istanbul
       outputs a valid out.json file:
     SyntaxError: Unexpected token g in JSON at position 7
      at JSON.parse (<anonymous>)
      at Context.<anonymous> (test\puppeteer-to-istanbul.js:15:29)
      at processImmediate (internal/timers.js:445:21)
```

**Comment by larsthorup** [comment]
Also the generated out.json does not contain valid JSON in this case, because the WIndows backslash path separator is not escaped in certain keys, as can be seen below:
![image](https://user-images.githubusercontent.com/1202959/81482251-dd2f2d80-9235-11ea-9645-827e6c8f2acf.png)

This leads to errors when trying to process this JSON file with `nyc report`

**Comment by larsthorup** [comment]
PR #54 with proposed fix. Tagging @SanterreJo as this relates to a previous commit of yours. Please comment here or on the PR if you see any issues with this fix.
